# Bisection Method

In [1]:
def bisection_fn(func):
    return func

def main():
    # Get the function as input
    func_str = input("Enter the function (in terms of x): ")
    func = lambda x: eval(func_str)

    a = float(input("Enter value of a: "))
    b = float(input("Enter value of b: "))
    i = int(input("Enter number of iterations: "))
    count = 0

    while count <= i:
        c = (a + b) / 2
        a1 = bisection_fn(a)
        c1 = bisection_fn(c)
        b1 = bisection_fn(b)

        if bisection_fn(c) * bisection_fn(b) < 0:
            a = c
        if c1 * a1 < 0:
            b = c

        count = count + 1
        print("\t count is: a  b  c  bisection_fn(a)  bisection_fn(b)  bisection_fn(c)", count, a, b, c, func(a), func(b), func(c))

    print("The final value of Root after all iterations is:", c)

if __name__ == "__main__":
    main()


Enter the function (in terms of x): x**2-49
Enter value of a: 6.5
Enter value of b: 7.1
Enter number of iterations: 5
	 count is: a  b  c  bisection_fn(a)  bisection_fn(b)  bisection_fn(c) 1 6.5 7.1 6.8 -6.75 1.4099999999999966 -2.760000000000005
	 count is: a  b  c  bisection_fn(a)  bisection_fn(b)  bisection_fn(c) 2 6.5 7.1 6.8 -6.75 1.4099999999999966 -2.760000000000005
	 count is: a  b  c  bisection_fn(a)  bisection_fn(b)  bisection_fn(c) 3 6.5 7.1 6.8 -6.75 1.4099999999999966 -2.760000000000005
	 count is: a  b  c  bisection_fn(a)  bisection_fn(b)  bisection_fn(c) 4 6.5 7.1 6.8 -6.75 1.4099999999999966 -2.760000000000005
	 count is: a  b  c  bisection_fn(a)  bisection_fn(b)  bisection_fn(c) 5 6.5 7.1 6.8 -6.75 1.4099999999999966 -2.760000000000005
	 count is: a  b  c  bisection_fn(a)  bisection_fn(b)  bisection_fn(c) 6 6.5 7.1 6.8 -6.75 1.4099999999999966 -2.760000000000005
The final value of Root after all iterations is: 6.8


# Least Square Approximation

In [2]:
import numpy as np
from sympy import symbols, Eq, solve

n = int(input("Enter the Total number of Data Points: "))
x = np.zeros(n)
y = np.zeros(n)

print("Enter the values of x")
for i in range(n):
    v = float(input("x"+str(i)+":"))
    x[i]=v
#print(x)


print("Enter the values of y")
for i in range(n):
    v = float(input("y"+str(i)+":"))
    y[i]=v
#print(y)

x = np.array(x)
y = np.array(y)
     
print(x)
print(y)

x = np.array(x)
y = np.array(y)

print(x)
print(y)

sumX= np.sum(x)
sumY = np.sum(y)
sumXY = np.sum(x*y)

sumX_square = np.sum(np.square(x))
print(sumX,sumY,sumX_square,sumXY)

a,b = symbols('a b')

eq1 = Eq(n*a + b*sumX - sumY)
eq2 = Eq(a*sumX + b*sumX_square - sumXY)

print(solve((eq1,eq2), (a,b)))


Enter the Total number of Data Points: 5
Enter the values of x
x0:0
x1:10
x2:20
x3:30
x4:40
Enter the values of y
y0:53.5
y1:59.5
y2:65.2
y3:70.6
y4:75.5
[ 0. 10. 20. 30. 40.]
[53.5 59.5 65.2 70.6 75.5]
[ 0. 10. 20. 30. 40.]
[53.5 59.5 65.2 70.6 75.5]
100.0 324.29999999999995 3000.0 7037.0
{a: 53.8400000000000, b: 0.551000000000000}


C:\Users\balan\AppData\Local\Temp\ipykernel_1932\866250649.py:42: SymPyDeprecationWarning: 

Eq(expr) with a single argument with the right-hand side
defaulting to 0 is deprecated. Use Eq(expr, 0) instead.

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-eq-expr
for details.

This has been deprecated since SymPy version 1.5. It
will be removed in a future version of SymPy.

  eq1 = Eq(n*a + b*sumX - sumY)


# Lagrange Interpolation

In [4]:
import numpy as np

n = int(input("Enter number of data points: "))

x = np.zeros((n))
y = np.zeros((n))

print("Enter data values: ")

for i in range(n):
    x[i] = float(input( 'x['+str(i)+']='))
    y[i] = float(input( 'y['+str(i)+']='))
    
xp = float(input("Enter interpolation point: "))

yp = 0

for i in range(n):
    p = 1
    
    for j in range(n):
        if i !=j:
            p = p*(xp - x[j])/(x[i] - x[j])
            
    yp = yp + p * y[i]
    
print('Interpolated value at %.3f is %.3f.' %(xp,yp) )

Enter number of data points: 5
Enter data values: 
x[0]=0.25
y[0]=-0.45
x[1]=0.75
y[1]=-0.6
x[2]=1.25
y[2]=0.7
x[3]=1.5
y[3]=1.88
x[4]=2
y[4]=6
Enter interpolation point: 1.1
Interpolated value at 1.100 is 0.176.


# Simpson's 1/3 Rule

In [7]:
def f(x):
    return 1/(1 + x**2)

def simpson13(x0,xn,n):
    h = (xn - x0) / n
    
    integration = f(x0) + f(xn)
    
    for i in range(1,n):
        k = x0 + i*h
        
        if i%2 == 0:
            integration = integration + 2*f(k)
        else:
            integration = integration + 4*f(k)
            
    integration = integration * h/3
    
    return integration 

lower_limit = float(input("Enter lower limit of integration: "))
upper_limit = float(input("Enter upper limit of integration: "))
sub_interval = int(input("Enter number of sub intervals: "))

result = simpson13(lower_limit, upper_limit, sub_interval)
print("Integration result: ", result)




Enter lower limit of integration: 0
Enter upper limit of integration: 6
Enter number of sub intervals: 6
Integration result:  1.3661734132322367


In [8]:
def simpson13(func, x0, xn, n):
    h = (xn - x0) / n
    integration = func(x0) + func(xn)

    for i in range(1, n):
        k = x0 + i * h
        if i % 2 == 0:
            integration += 2 * func(k)
        else:
            integration += 4 * func(k)

    integration = integration * h / 3
    return integration

# Take the function from the user as a string and convert it to a callable function
func_str = input("Enter the function (in terms of x): ")
func = lambda x: eval(func_str)

lower_limit = float(input("Enter lower limit of integration: "))
upper_limit = float(input("Enter upper limit of integration: "))
sub_interval = int(input("Enter number of sub intervals: "))

result = simpson13(func, lower_limit, upper_limit, sub_interval)
print("Integration result: ", result)


Enter the function (in terms of x): 1/(1 + x**2)
Enter lower limit of integration: 0
Enter upper limit of integration: 6
Enter number of sub intervals: 6
Integration result:  1.3661734132322367


# Simpson's 3/8 Method

In [13]:
# Simpson's 3/8 Rule
def simpson38(func, x0, xn, n):
    h = (xn - x0) / n
    integration = func(x0) + func(xn)

    for i in range(1, n):
        k = x0 + i * h
        if i % 3 == 0:
            integration = integration + 2 * func(k)
        else:
            integration = integration + 3 * func(k)

    integration = integration * 3 * h / 8
    return integration

# Take the function from the user as a string and convert it to a callable function
func_str = input("Enter the function (in terms of x): ")
func = lambda x: eval(func_str)

lower_limit = float(input("Enter lower limit of integration: "))
upper_limit = float(input("Enter upper limit of integration: "))
sub_interval = int(input("Enter number of sub intervals: "))

result = simpson38(func, lower_limit, upper_limit, sub_interval)
print("Integration result: ", result)

Enter the function (in terms of x): 1/(1 + x**2)
Enter lower limit of integration: 0
Enter upper limit of integration: 1
Enter number of sub intervals: 6
Integration result:  0.7853958624450428


# Birge-Vieta Method

In [11]:
def f(x):
    return x**4+x**3+5*x**2+4*x+4

p0 = float(input("Enter value of initial approximate root p0: "))
a0 = float(input("Enter value of a0: "))
a1 = float(input("Enter value of a1: "))
a2 = float(input("Enter value of a2: "))
a3 = float(input("Enter value of a3: "))
a4 = float(input("Enter value of a4: "))
i = int(input("Enter no. of iterations: "))

count = 1
while (count<=i):
    b0=a0
    b1=a1+p0*b0
    b2=a2+p0*b1
    b3=a3+p0*b2
    b4=a4+p0*b3
    c0=b0
    c1=b1+p0*c0
    c2=b2+p0*c1
    c3=b3+p0*c2
    p1=p0-(b4/c3)
    print("Iteration:",count)
    print("New root is:",p1)
    p0 = p1
    count = count+1
    
    

Enter value of initial approximate root p0: 1
Enter value of a0: 1
Enter value of a1: 1
Enter value of a2: 5
Enter value of a3: 4
Enter value of a4: 4
Enter no. of iterations: 2
Iteration: 1
New root is: 0.2857142857142857
Iteration: 2
New root is: -0.48992822412595505


In [13]:
def birge_vieta():
    func_str = input("Enter the function (in terms of x): ")
    func = lambda x: eval(func_str)

    p0 = float(input("Enter value of initial approximate root p0: "))
    a0 = float(input("Enter value of a0: "))
    a1 = float(input("Enter value of a1: "))
    a2 = float(input("Enter value of a2: "))
    a3 = float(input("Enter value of a3: "))
    a4 = float(input("Enter value of a4: "))
    i = int(input("Enter the number of iterations: "))

    count = 1
    while count <= i:
        b0 = a0
        b1 = a1 + p0 * b0
        b2 = a2 + p0 * b1
        b3 = a3 + p0 * b2
        b4 = a4 + p0 * b3
        c0 = b0
        c1 = b1 + p0 * c0
        c2 = b2 + p0 * c1
        c3 = b3 + p0 * c2
        p1 = p0 - (b4 / c3)
        print("Iteration:", count)
        print("New root is:", p1)
        p0 = p1
        count += 1

birge_vieta()


Enter the function (in terms of x): x**4+x**3+5*x**2+4*x+4
Enter value of initial approximate root p0: 1
Enter value of a0: 1
Enter value of a1: 1
Enter value of a2: 5
Enter value of a3: 4
Enter value of a4: 4
Enter the number of iterations: 2
Iteration: 1
New root is: 0.2857142857142857
Iteration: 2
New root is: -0.48992822412595505


In [4]:
def birge_vieta_solver(coefficients, initial_approx_root, num_iterations):
    p0 = initial_approx_root

    count = 1
    while count <= num_iterations:
        n = len(coefficients) - 1  # Degree of the polynomial
        b = [0] * (n + 1)
        c = [0] * (n + 1)

        b[0] = coefficients[0]
        c[0] = coefficients[0]

        for i in range(1, n + 1):
            b[i] = coefficients[i] + p0 * b[i - 1]
            c[i] = b[i] + p0 * c[i - 1]

        p1 = p0 - (b[n] / c[n - 1])

        print("Iteration:", count)
        print("New root is:", p1)

        p0 = p1
        count += 1

    return p0

# Get the user's input for coefficients and initial approximate root
equation_str = input("Enter the coefficients of the polynomial equation (e.g., '1 1 5 4 4'): ")
coefficients = list(map(float, equation_str.split()))
initial_approx_root = float(input("Enter the initial approximate root p0: "))
num_iterations = int(input("Enter the number of iterations: "))

# Call the function to solve for the root
result = birge_vieta_solver(coefficients, initial_approx_root, num_iterations)
print("Final root is:", result)


Enter the coefficients of the polynomial equation (e.g., '1 1 5 4 4'): 1 1 5 4 4 
Enter the initial approximate root p0: 1
Enter the number of iterations: 2
Iteration: 1
New root is: 0.2857142857142857
Iteration: 2
New root is: -0.48992822412595505
Final root is: -0.48992822412595505


# 4th Order Runge Kutta Method

In [10]:
def rk4_solver(x0, y0, xn, n, equation):
    # Function to be solved
    f = lambda x, y: eval(equation)

    # Calculating step size
    h = (xn - x0) / n

    print('\n--------SOLUTION--------')
    print('-------------------------')
    print('x0\ty0\tyn')
    print('-------------------------')
    
    for i in range(n):
        k1 = h * f(x0, y0)
        k2 = h * f(x0 + h / 2, y0 + k1 / 2)
        k3 = h * f(x0 + h / 2, y0 + k2 / 2)
        k4 = h * f(x0 + h, y0 + k3)
        k = (k1 + 2 * k2 + 2 * k3 + k4) / 6
        yn = y0 + k
        print('%.4f\t%.4f\t%.4f' % (x0, y0, yn))
        print('-------------------------')
        y0 = yn
        x0 = x0 + h

    print('\nAt x=%.4f, y=%.4f' % (xn, yn))

# Inputs
print('Enter initial conditions:')
x0 = float(input('x0 = '))
y0 = float(input('y0 = '))

print('Enter calculation point: ')
xn = float(input('xn = '))

print('Enter number of steps:')
step = int(input('Number of steps = '))

equation_str = input("Enter the function (in terms of x and y): ")

# RK4 method call
rk4_solver(x0, y0, xn, step, equation_str)


Enter initial conditions:
x0 = 0
y0 = 1
Enter calculation point: 
xn = 1
Enter number of steps:
Number of steps = 2
Enter the function (in terms of x and y): x+y

--------SOLUTION--------
-------------------------
x0	y0	yn
-------------------------
0.0000	1.0000	1.7969
-------------------------
0.5000	1.7969	3.4347
-------------------------

At x=1.0000, y=3.4347


# Gauss Siedal Method

In [11]:
def seidel(a, x ,b): 
    #Finding length of a(3)        
    n = len(a)                    
    # for loop for 3 times as to calculate x, y , z 
    for j in range(0, n):         
        # temp variable d to store b[j] 
        d = b[j]                   
          
        # to calculate respective xi, yi, zi 
        for i in range(0, n):      
            if(j != i): 
                d-=a[j][i] * x[i] 
        # updating the value of our solution         
        x[j] = d / a[j][j] 
    # returning our updated solution            
    return x     
   
# int(input())input as number of variable to be solved                 
n = 3                              
a = []                             
b = []         
# initial solution depending on n(here n=3)                      
x = [0, 0, 0]                         
a = [[4, 1, 2],[3, 5, 1],[1, 1, 3]] 
b = [4,7,3] 
print(x) 
  
#loop run for m times depending on m the error value 
for i in range(0, 25):             
    x = seidel(a, x, b) 
    #print each time the updated solution 
    print(x)           

[0, 0, 0]
[1.0, 0.8, 0.39999999999999997]
[0.6000000000000001, 0.9599999999999997, 0.48000000000000004]
[0.52, 0.9919999999999998, 0.49600000000000005]
[0.504, 0.9983999999999998, 0.4992000000000001]
[0.5008, 0.99968, 0.49984]
[0.5001599999999999, 0.9999360000000002, 0.4999679999999999]
[0.500032, 0.9999872, 0.4999936]
[0.5000064, 0.9999974400000001, 0.49999871999999995]
[0.50000128, 0.999999488, 0.4999997439999999]
[0.500000256, 0.9999998976000001, 0.49999994880000004]
[0.5000000512, 0.9999999795199999, 0.4999999897600001]
[0.50000001024, 0.999999995904, 0.499999997952]
[0.500000002048, 0.9999999991808, 0.49999999959040003]
[0.5000000004095999, 0.9999999998361601, 0.49999999991808003]
[0.50000000008192, 0.9999999999672321, 0.49999999998361594]
[0.500000000016384, 0.9999999999934465, 0.49999999999672307]
[0.5000000000032768, 0.9999999999986894, 0.4999999999993445]
[0.5000000000006554, 0.9999999999997378, 0.49999999999986894]
[0.500000000000131, 0.9999999999999478, 0.49999999999997374]
